import type { MarketData } from "../types";

export const marketData: MarketData = {
  americas: [
    {
      id: "BTC",
      num: "11)",
      rmi: "RMI",
      instrumentType: "Crypto price",
      sourceSymbol: "BTCUSDT",
      value: 63874.21,
      change: 741.38,
      pctChange: 1.17,
      avat: 22.84,
      time: "10:46",
      ytd: 42.18,
      ytdCur: 42.18,
    },
    {
      id: "IBIT",
      num: "12)",
      rmi: "RMI",
      instrumentType: "ETF price",
      sourceSymbol: "IBIT",
      value: 63.75,
      change: 0.64,
      pctChange: 1.01,
      avat: 10.12,
      time: "10:46",
      ytd: 41.91,
      ytdCur: 41.91,
    },
    {
      id: "MSTR",
      num: "13)",
      rmi: "RMI",
      instrumentType: "Stock price",
      sourceSymbol: "MSTR",
      value: 1342.4,
      change: 28.15,
      pctChange: 2.14,
      avat: 11.26,
      time: "10:46",
      ytd: 68.21,
      ytdCur: 68.21,
    },
    {
      id: "MARA",
      num: "14)",
      rmi: "RMI",
      instrumentType: "Stock price",
      sourceSymbol: "MARA",
      value: 19.82,
      change: 0.44,
      pctChange: 2.27,
      avat: 9.18,
      time: "10:46",
      ytd: 35.13,
      ytdCur: 35.13,
    },
    {
      id: "RIOT",
      num: "15)",
      rmi: "RMI",
      instrumentType: "Stock price",
      sourceSymbol: "RIOT",
      value: 11.53,
      change: 0.19,
      pctChange: 1.68,
      avat: 7.96,
      time: "10:46",
      ytd: 28.07,
      ytdCur: 28.07,
    },
    {
      id: "CLSK",
      num: "16)",
      rmi: "RMI",
      instrumentType: "Stock price",
      sourceSymbol: "CLSK",
      value: 16.27,
      change: 0.37,
      pctChange: 2.33,
      avat: 8.02,
      time: "10:46",
      ytd: 31.84,
      ytdCur: 31.84,
    },
    {
      id: "HUT",
      num: "17)",
      rmi: "RMI",
      instrumentType: "Stock price",
      sourceSymbol: "HUT",
      value: 11.44,
      change: 0.26,
      pctChange: 2.33,
      avat: 6.44,
      time: "10:46",
      ytd: 25.11,
      ytdCur: 25.11,
    },
    {
      id: "IREN",
      num: "18)",
      rmi: "RMI",
      instrumentType: "Stock price",
      sourceSymbol: "IREN",
      value: 8.31,
      change: 0.15,
      pctChange: 1.84,
      avat: 5.18,
      time: "10:46",
      ytd: 19.24,
      ytdCur: 19.24,
    },
    {
      id: "CORZ",
      num: "19)",
      rmi: "RMI",
      instrumentType: "Stock price",
      sourceSymbol: "CORZ",
      value: 13.89,
      change: 0.35,
      pctChange: 2.59,
      avat: 6.75,
      time: "10:46",
      ytd: 37.52,
      ytdCur: 37.52,
    },
  ],
  emea: [
    {
      id: "SPX",
      num: "21)",
      rmi: "RMI",
      instrumentType: "Index level",
      sourceSymbol: "^GSPC",
      value: 5157.32,
      change: 24.17,
      pctChange: 0.47,
      avat: 3.31,
      time: "10:46",
      ytd: 8.22,
      ytdCur: 8.22,
    },
    {
      id: "NDX",
      num: "22)",
      rmi: "RMI",
      instrumentType: "Index level",
      sourceSymbol: "^NDX",
      value: 18290.21,
      change: 132.74,
      pctChange: 0.73,
      avat: 4.75,
      time: "10:46",
      ytd: 10.67,
      ytdCur: 10.67,
    },
    {
      id: "DXY",
      num: "23)",
      rmi: "RMI",
      instrumentType: "Forex pair",
      sourceSymbol: "DX-Y.NYB",
      value: 104.11,
      change: 0.22,
      pctChange: 0.21,
      avat: -1.48,
      time: "10:46",
      ytd: 2.31,
      ytdCur: 2.31,
    },
  ],
  asiaPacific: [
    {
      id: "SHY",
      num: "31)",
      rmi: "RMI",
      instrumentType: "ETF price",
      sourceSymbol: "SHY",
      value: 81.44,
      change: -0.06,
      pctChange: -0.07,
      avat: 1.26,
      time: "10:46",
      ytd: -0.42,
      ytdCur: -0.42,
    },
    {
      id: "IEF",
      num: "32)",
      rmi: "RMI",
      instrumentType: "ETF price",
      sourceSymbol: "IEF",
      value: 94.16,
      change: -0.18,
      pctChange: -0.19,
      avat: 1.78,
      time: "10:46",
      ytd: -1.26,
      ytdCur: -1.26,
    },
    {
      id: "GOLD",
      num: "33)",
      rmi: "RMI",
      instrumentType: "Commodity price",
      sourceSymbol: "XAUUSD=X",
      value: 2340.83,
      change: 11.42,
      pctChange: 0.49,
      avat: 2.84,
      time: "10:46",
      ytd: 9.57,
      ytdCur: 9.57,
    },
    {
      id: "SILVER",
      num: "34)",
      rmi: "RMI",
      instrumentType: "Commodity price",
      sourceSymbol: "XAGUSD=X",
      value: 30.12,
      change: 0.21,
      pctChange: 0.7,
      avat: 1.91,
      time: "10:46",
      ytd: 12.34,
      ytdCur: 12.34,
    },
  ],
};
